# Kubernetes Resources for Development kOps Cluster

apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
    environment: development

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
  namespace: development
  labels:
    app: gitops-app
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
        environment: development
    spec:
      containers:
      - name: app
        image: <ECR_REPO_URL>:<IMAGE_TAG>
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: gitops-app
  namespace: development
  labels:
    app: gitops-app
spec:
  type: ClusterIP
  selector:
    app: gitops-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http

