# Application deployment manifest for kOps development cluster
# Similar structure to EKS but with dev-specific configurations

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/gitops-platform.git
    targetRevision: main
    path: gitops/clusters/kops-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
# Kubernetes Deployment (Dev)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: app
        image: <ECR_REPO_URL>:<IMAGE_TAG>
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: gitops-app
  namespace: development
spec:
  selector:
    app: gitops-app
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP

